name = "SyslogLoggingCompose"
uuid = "f9d8535d-faa2-4676-9d3d-5d546174f1ea"
authors = ["Tanmay Mohapatra <tanmaykm@gmail.com>"]
license = "MIT"
desc = "Enable SyslogLogging for LogCompose"
version = "0.1.0"

[deps]
LogCompose = "8416b438-731e-11ea-2421-05f642269042"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
SyslogLogging = "0c4b0c42-68ec-11ea-3bc9-e7fb6e00ea0f"

[compat]
julia = "1"
SyslogLogging = "0.1"
LogCompose = "0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
